_parent_: configs/base.yaml

tb: false
batch_size: 1                                                 # batch size (not used for NeRF/BARF)
load: configs/pretrained_models/matchnerf_3v.pth
separate_save: true                                           # save images separately for further evaluation

nerf:
    rand_rays_test: 20480                                         # number of random rays for each step

data_test:
    tnt:
        root_dir: data/tnt_data
        dataset_name: tnt                                            # dataset name
        img_wh: [960, 640]                                   # input image sizes [width, height]
        num_workers: 4                                          # number of parallel workers for data loading
        max_len: -1
        scene_list:
        test_views_method: nearest
        eval_mode: mvsnerf
        nf_mode: minmax
        n_views: 3
